identifier: orion_92
name: Orion 92
type: keyboard
arch: arm
ram: 256
flash: 1024
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - ble
  - counter
  - gpio
  - i2c
  - kscan
  - usb_device
